### ISSUE TITLE
bug: failure to parse AssetTracesItem

### ISSUE THREAD

**Issue by conorsch** [prax-wallet/registry#85]
Trying to rerun the `tools/compiler` script on current main (61359f51d01c42a5b0fcae180c8a530e47dfa613), I encounter an error:

```
❯ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/penumbra-registry`
Error: RequestError(reqwest::Error { kind: Decode, source: Error("data did not match any variant of untagged enum AssetTracesItem", line: 2
385, column: 8) })
```

Presumably upstream content in the cosmos chain-registry repo has changed in a breaking way, but identifying the specific failure is a bit tricky, without more verbose logging (see #74).

**Comment by grod220** [comment]
Indeed, the schema was updated. https://github.com/prax-wallet/registry/pull/88 unblocks this.
