### ISSUE TITLE
Document using typify to generate Rust types

### ISSUE THREAD

**Issue by conorsch** [prax-wallet/registry#86]
The `tools/compiler` uses code generated by the [typify](https://github.com/oxidecomputer/typify/) tool:

https://github.com/prax-wallet/registry/blob/61359f51d01c42a5b0fcae180c8a530e47dfa613/tools/compiler/src/github/assetlist_schema.rs#L1-L2

However, I'm unable to rerun that tool on the upstream chain-registry json schema:

```
❯ curl -sSf -O https://raw.githubusercontent.com/cosmos/chain-registry/master/assetlist.schema.json

❯ cargo typify ./assetlist.schema.json
The application panicked (crashed).
Message:  not implemented: if/then/else schemas are not supported
Location: /home/conor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typify-impl-0.1.0/src/merge.rs:291

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

I also tried a much older version of the schema file, from about ~2024-04, around the time the `prax-wallet/registry` tool was initially written, but even those schema files contained if/else statements and were therefore rejected by typify. 

So, how were the rust types currently in the repo generated? Was the json schema manually edited before running typify? Are there additional steps we can document or codify so that the workflow is reproducible and maintainable into the future?

**Comment by grod220** [comment]
The little documentation I originally wrote is certainly not sufficient. Sorry about that. The schema includes a single if/else clause which sadly causes Typify to throw. Removing that one manually, allows it to work. Given this, I don't think there's a programmatic way we can keep the schema updated. But given how many teams depend on this repo, I'd imagine it rarely changes (maybe naive thinking though).

I'll create a PR to update to the latest and add more documentation.
